dist: xenial
env:
  global:
    - CC_TEST_REPORTER_ID=ade71cd653792da684ee23c3f23101c2084957fad16260fbf681c37e398deb29
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
language: python
python:
  - 3.6
  - 3.5
before_install: 
  - sudo apt-get update
  - sudo apt-get install -y libgirepository1.0-dev libcairo2-dev libcairo2
  - pip install pycairo
install: pip install .
script: python setup.py test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
